#!/bin/bash

echo "%sudo ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/dev > /dev/null

echo "---- Updatating Ubuntu... ----"
sudo apt update
sudo apt upgrade -y

echo "--- Installing network and wsl utilities ---"
sudo apt install wslu libnss3-tools -y

echo "---- Installing PHPStorm... ----"
sudo snap install phpstorm --classic

echo "---- Installing VSCode... ----"
sudo snap install code --classic

echo "---- Installing Google Chrome ----"
sudo apt install curl software-properties-common apt-transport-https ca-certificates -y
curl -fSsL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/google-chrome.gpg > /dev/null
echo deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main | sudo tee /etc/apt/sources.list.d/google-chrome.list
sudo apt update
sudo apt install google-chrome-stable -y

echo "---- Installing Firefox ---- "
sudo snap install firefox

echo "--- Installing Docker... https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository ----"
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

echo "---- Post Docker installation steps. https://docs.docker.com/engine/install/linux-postinstall/ ----"
# Post install instruction.
sudo usermod -aG docker $USER 
sudo systemctl enable docker.service
sudo systemctl enable containerd.service

echo "---- Installing DDEV https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#ddev-installation-linux ----"
curl -fsSL https://ddev.com/install.sh | bash

echo "---- Setting up mkcert ----"
echo 'export CAROOT=/mnt/$(wslvar USERPROFILE | sed "s/\\\/\\//g" | sed "s/://g" | tr [:upper:] [:lower:])/AppData/Local/mkcert' | sudo tee -a /etc/profile