#!/bin/bash

echo "---- Updatating Ubuntu... ----"
sudo apt update
sudo apt upgrade -y

echo "---- Installing PHPStorm... ----"
sudo snap install phpstorm --classic

echo "---- Installing VSCode... ----"
sudo snap install code --classic

echo "---- Installing Google Chrome ----"
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo apt-get install -f -y

echo "---- Installing GIT ----"
sudo apt install git -y

echo "--- Installing Docker... https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository ----"
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

echo "---- Post Docker installation steps. https://docs.docker.com/engine/install/linux-postinstall/ ----"
# Post install instruction.
sudo usermod -aG docker $USER 
sudo systemctl enable docker.service
sudo systemctl enable containerd.service

echo "--- Installing DDEV https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#ddev-installation-linux ----"
curl -fsSL https://ddev.com/install.sh | bash
sudo apt install mkcert -y
mkcert -install
